---

# AFS cell name
afs_cell: example.com

# cell organization name
afs_cell_description: Example

# kerberos realm
afs_realm: EXAMPLE.COM

# openafs yum repo for client packages
afs_openafs_client_repourl: https://download.sinenomine.net/openafs/bins/1.8.2/rhel7/$basearch

# Installation method, one of: package-manager, make-install
afs_client_install_method: package-manager

# Install kernel module with DKMS
afs_client_install_dkms: no

# 'build' installation git repo url
afs_client_build_repo: https://github.com/openafs/openafs.git

# 'build' installation method path
afs_client_build_path: /usr/local/src/openafs-client

# 'build' installation method git reference
afs_client_build_version: master

# openafs kmod package release prefix
afs_openafs_kmod_prefix: 1

# afs filesystem mount point
afs_cacheinfo_mount: /afs

# afs cache mount point
afs_cacheinfo_cache: /usr/vice/cache

# afs cache size
# TODO: create partition or autodecte
afs_cacheinfo_size: 50000

# afsd options
afs_afsd_opts: -dynroot -fakestat -afsdb
