---

# AFS cell name
afs_cell: example.com

# cell organization name
afs_cell_description: Example

# kerberos realm
afs_realm: EXAMPLE.COM

afs_openafs_client_tmpdir: /tmp/ansible/openafs

# openafs yum repo for client packages
afs_openafs_client_repourl: https://download.sinenomine.net/openafs/bins/1.8.2/el7/$basearch

# Installation method.
# One of: 'package-manager', 'rsync'
afs_client_install_method: package-manager

# Install kernel module with DKMS
afs_client_install_dkms: no

# Build options for rsync install method.
afs_client_build_force: no
afs_client_build_builddir: "/usr/local/src/openafs_client"
afs_client_build_destdir: "/tmp/openafs_client"
afs_client_build_fetch_method: "git"
afs_client_build_git_repo: "https://github.com/openafs/openafs"
afs_client_build_git_ref: "master"

# openafs kmod package release prefix
afs_openafs_kmod_prefix: 1

# afs filesystem mount point
afs_cacheinfo_mount: /afs

# afs cache mount point
afs_cacheinfo_cache: /usr/vice/cache

# afs cache size
# TODO: create partition or autodecte
afs_cacheinfo_size: 50000

# afsd options
afs_afsd_opts: -dynroot -fakestat -afsdb
