---
- name: Make partition directory
  file:
    path: /vicep{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items: "{{ partitions.split(',') }}"
  when: partitions is defined

- name: Enable always attach mode for partition
  copy:
    content: ""
    dest: /vicep{{ item }}/AlwaysAttach
    force: no
    owner: root
    group: root
    mode: 0600
  with_items: "{{ partitions.split(',') }}"
  when: partitions is defined

