---
- name: Write the keytab file
  command: >
    kadmin
    -r "{{ realm }}"
    -p "{{ admin_principal }}"
    -w "{{ admin_password }}"
    -q 'ktadd -norandkey -k {{ afsconfdir }}/rxkad.keytab afs/{{ cell }}@{{ realm }}'
  args:
    creates: "{{ afsconfdir }}/rxkad.keytab"

- name: Get asetkey usage
  command: asetkey
  register: asetkey_usage
  changed_when: false
  failed_when: false

- name: Scan keytab for key versions and encryption types
  shell: >
    klist -e -k {{ afsconfdir }}/rxkad.keytab |
    sed '1,3d' |
    sed 's/[()]//g' |
    awk '$2 == "afs/{{ cell }}@{{ realm }}" && $3 !~ /^des/
    { printf("- kvno: %d\n  enc: %s\n", $1, $3) }'
  changed_when: False
  register: klist_result
  when: "'asetkey add <type> <kvno> <subtype> <key>' in asetkey_usage.stderr"

- name: Set the service keys
  command: >
    asetkey add rxkad_krb5
    {{ item.kvno }}
    {{ kerberos_eno[item.enc] }}
    {{ afsconfdir }}/rxkad.keytab
    afs/{{ cell }}@{{ realm }}
  with_items: "{{ klist_result.stdout | from_yaml }}"
  when: "'asetkey add <type> <kvno> <subtype> <key>' in asetkey_usage.stderr"
