---
- name: Generate csdb.yaml
  hosts: afs_databases
  tasks:
    - import_role:
        name: openafs_common
        tasks_from: generate_csdb

- name: Converge
  hosts: all
  tasks:
    - import_role:
        name: openafs_krbserver

    - import_role:
        name: openafs_krbclient

    - import_role:
        name: openafs_server

    - import_role:
        name: openafs_client

    - import_role:
        name: openafs_robotest
