---
# afs cell name
afs_cell: example.com

# kerberos realm name
afs_realm: EXAMPLE.COM

# Kerberos and AFS admin principal
afs_admin_principal: admin

# Kerberos and AFS admin password (no default)
# afs_admin_password:

# primary kerberos kdc hostname
afs_kdc: "{{ groups['afs_kdcs'][0] }}"

# primary fileserver hostname
afs_root_server: "{{ groups['afs_fileservers'][0] }}"

# primary fileserver afs partition id
afs_root_part: a

# afsd options
# TODO: should detect or get this from the client role.
afs_afsd_opts: -dynroot -fakestat -afsdb
