---
# afs cell name
cell: example.com

# kerberos realm name
realm: EXAMPLE.COM

# Kerberos and AFS admin principal
admin_principal: admin

# Kerberos and AFS admin password (no default)
# admin_password:

# primary kerberos kdc hostname
kdc: "{{ groups['kdcs'][0] }}"

# primary fileserver hostname
root_server: "{{ groups['fileservers'][0] }}"

# primary fileserver afs partition id
root_part: a

# afsd options
# TODO: should detect or get this from the client role.
opt_afsd: -dynroot -fakestat -afsdb
