---
afs_cell: example.com
afs_realm: EXAMPLE.COM

afs_volumes:
  - name: test

afs_users:
  - name: user1
  - name: user2
  - name: user3
  - name: user4

afs_groups:
  - name: group1
    members:
      - user1
      - user2
