---
- name: Prevent services from starting during install
  become: yes
  copy:
    src: "Debian/policy-rc.d"
    dest: "/usr/sbin/policy-rc.d"
    mode: "0755"
    backup: yes
  register: change_policy_rc_result

- name: Install kerberos server
  become: yes
  apt:
    name:
      - krb5-kdc
      - krb5-admin-server
    state: present
    update_cache: yes

- name: Remove custom policy-rc file
  become: yes
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
  when: change_policy_rc_result.changed
