---
# Post rsync installation tasks for CentOS 6.x.

- name: Update shared library cache
  command: /sbin/ldconfig
  changed_when: false

- name: Install startup options config file
  copy:
    # This file has sections for the client and server.
    # Use force:no to avoid clobbering if already installed by the client.
    src: centos6/openafs.sysconfig
    dest: /etc/sysconfig/openafs
    force: no

- name: Set bosserver startup options
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers
