---
# Post rsync install tasks for generic debian.
#
# XXX: Debian doesn't have a /etc/sysconf/ directory. Change this to
#      be debian-like.
#
- name: Update shared library cache
  become: yes
  command: /sbin/ldconfig
  changed_when: false

- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: Install startup options config file
  become: yes
  copy:
    # This file has sections for the client and server.
    # Use force:no to avoid clobbering if already installed by the client.
    src: Debian/openafs.sysconfig
    dest: /etc/sysconfig/openafs
    force: no

- name: Set bosserver startup options
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers
