---
- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit afs3 traffic
  firewalld:
    port: 7000-7009/udp
    state: enabled
    immediate: yes
    permanent: yes

- name: Check cache directory
  file:
    state: directory
    path: "{{ afscachedir }}"
    mode: 0700
    owner: root
    group: root
