---
- name: Install Setools
  become: yes
  yum:
    name:
      - policycoreutils-python
      - setools-console
    state: present

- name: Add epel yum repo
  become: yes
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install packages
  become: yes
  yum:
    name:
      - git
      - python-pip
    state: present
