---
# AFS cell name.
afs_cell: example.com

# Kerberos realm name.
afs_realm: "{{ afs_cell | upper }}"

# Path to files on controller to be uploaded to remote nodes.
afs_cell_files: "{{ '~/.ansible-openafs' | expanduser }}/{{ afs_cell }}"

# Log directory on remote nodes.
afs_logdir: /var/log/ansible-openafs

# Temporary directory on remote nodes.
afs_tmpdir: /tmp/ansible-openafs

# Installation method; one of; managed, package, bdist, scm
afs_install_method: managed

# Yum repository url or path for 'managed' installs on yum based systems.
afs_yum_repo: "https://download.sinenomine.net/openafs/rpms/el$releasever/$basearch"

# Path to installation tarball on controller for non-managed installs.
afs_install_archive: ""

# Git repository and branch info for builds and scm based installs.
afs_git_repo: "git://git.openafs.org/openafs.git"
afs_git_version: "master"
