---
# AFS cell name.
afs_cell: example.com

# Kerberos realm name.
afs_realm: "{{ afs_cell | upper }}"

# Path to files on controller to be uploaded to remote nodes.
afs_cell_files: "{{ '~/.ansible-openafs' | expanduser }}/{{ afs_cell }}"

# CellServDB information (default is undefined.)
# afs_csdb:

# Path to the CellServDB yaml file on the controller.
afs_csdb_file: "{{ afs_cell_files }}/csdb.yaml"

# Temporary directory on remote nodes.
afs_tmpdir: /tmp/ansible-openafs

# Project build directory on remote nodes.
afs_topdir: ~/openafs

# Installation method; one of; managed, package, bdist, sdist, scm, none
afs_install_method: managed

# Yum repository url or path for 'managed' installs on yum based systems.
afs_yum_repo: "https://download.sinenomine.net/openafs/rpms/el$releasever/$basearch"

# Path to installation tarball on controller for non-managed installs.
afs_install_archive: ""

# Git repository and branch info for builds and scm based installs.
afs_git_repo: "git://git.openafs.org/openafs.git"
afs_git_version: "master"
