---
- name: Prevent services from starting during install
  copy:
    src: "debian/policy-rc.d"
    dest: "/usr/sbin/policy-rc.d"
    mode: "0755"
    backup: yes

- name: Install OpenAFS packages
  apt:
    state: present
    install_recommends: no
    update_cache: yes
    name:
      - openafs-client
      - openafs-modules-dkms
      - openafs-krb5
  notify:
    - Restart OpenAFS client

- name: Ensure there are no policy-rc files
  file:
    path: "/usr/sbin/policy-rc.d"
    state: absent
