---
- name: "CentOS-7: Add EPEL repository"
  become: yes
  yum:
    state: present
    name: epel-release
    update_cache: yes
  tags: root

- name: "CentOS-7: Install development packages"
  become: yes
  yum:
    state: present
    name:
      - autoconf
      - automake
      - bison
      - flex
      - fuse-devel
      - gcc
      - git
      - glibc-devel
      - "kernel-devel-uname-r == {{ ansible_kernel }}"
      - krb5-devel
      - libtool
      - make
      - ncurses-devel
      - pam-devel
      - perl-devel
      - perl-ExtUtils-Embed
      - redhat-rpm-config
      - rpm-build
      - swig
      - wget
  tags: root
