---

# afs cell name
afs_cell: example.com

# cell organization name
afs_cell_description: Example

# kerberos realm name
afs_realm: EXAMPLE.COM

# Kerberos and AFS admin principal
afs_admin_principal: admin

# Kerberos and AFS admin password (no default)
# afs_admin_password:

# openafs yum repo for server packages
afs_openafs_server_repourl: https://download.sinenomine.net/openafs/bins/1.8.2/rhel7/$basearch

# selinux mode
afs_selinux_mode: enforcing

# Installation method, one of: package-manager, make-install
afs_server_install_method: package-manager

# 'build' installation git repo url
afs_server_build_repo: https://github.com/openafs/openafs.git

# 'build' installation method path
afs_server_build_path: /usr/local/src/openafs-server

# 'build' installation method git reference
afs_server_build_version: master

afs_server_build_force: no
afs_server_build_builddir: "/usr/local/src/openafs_server"
afs_server_build_destdir: "/tmp/openafs_server"
afs_server_build_fetch_method: "git"
afs_server_build_git_repo: "https://github.com/openafs/openafs"
afs_server_build_git_ref: "master"

# fileserver variation, one of: fs, dafs
afs_fileserver_type: dafs

# bosserver options
afs_bosserver_opts:

# ptserver options
afs_ptserver_opts:

# vlserver options
afs_vlserver_opts:

# DAFS fileserver options
afs_dafileserver_opts: -L

# DAFS volume server options
afs_davolserver_opts:

# DAFS salvage server options
afs_salvageserver_opts:

# DAFS salvager options
afs_dasalvager_opts:

# Legacy fileserver options
afs_fileserver_opts:

# Legacy volume server options
afs_volserver_opts:

# Legacy salvager options
afs_salvager_opts:

# Master kerberos kdc
afs_kdc: "{{ groups['afs_kdcs'][0] }}"

# Primary fileserver hostname
afs_root_server: "{{ groups['afs_fileservers'][0] }}"

# Primary fileserver vice partition id
afs_root_part: a
