---
cell: example.com
openafs_org: Example
realm: EXAMPLE.COM

openafs_server_repourl: https://download.sinenomine.net/openafs/bins/1.8.2/rhel7/$basearch
selinux_mode: enforcing
server_install_method: yum

enable_dafs: true
opt_bosserver:
opt_ptserver:
opt_vlserver:
opt_dafileserver: -L
opt_davolserver:
opt_salvageserver:
opt_dasalvager:

kdc: "{{ groups['kdcs'][0] }}"
root_server: "{{ groups['fileservers'][0] }}"
root_part: a
