---
- name: Unsupported install method or platform
  fail:
    msg: >
      Searched
      '{{ role_path }}/tasks/install/{{ afs_install_method }}-{{ ansible_os_family | lower }}-{{ afs_module_install_method }}.yaml',
      '{{ role_path }}/tasks/install/{{ afs_install_method }}-{{ ansible_os_family | lower }}.yaml',
      '{{ role_path }}/tasks/install/{{ afs_install_method }}.yaml'
