---
- name: Load OS specific variables
  include_vars: "{{ ansible_distribution }}.yaml"

- name: Include OS specific tasks
  include_tasks: "{{ ansible_distribution }}.yaml"

- name: Update cell configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ viceetcdir }}/{{ item }}"
    mode: 0644
  with_items:
    - CellServDB.local
    - ThisCell
    - cacheinfo

# Fixup the contexts for the items created during
# setup while unconfined_t
- name: "Fix contexts for selinux"
  command: restorecon -ir "{{ item }}"
  with_items:
    -  /usr/vice
    - "{{ afscachedir }}"

- name: Start OpenAFS client
  service:
    state: started
    name: openafs-client
