---
- name: Load OS specific variables
  include_vars: "{{ ansible_distribution }}.yaml"

- include_tasks: "{{ ansible_distribution }}/pre-install.yaml"
- include_tasks: "{{ ansible_distribution }}/install.yaml"
- include_tasks: "{{ ansible_distribution }}/post-install.yaml"
- include_tasks: common/config.yaml
- include_tasks: "{{ ansible_distribution }}/post-config.yaml"

- name: Start OpenAFS client
  service:
    state: started
    name: openafs-client
