---
- include_tasks: "{{ ansible_os_family|lower }}/install-build-tools.yaml"

- name: Create build directory
  file:
    state: directory
    path: "{{ afs_client_build_path }}"

- name: Clone OpenAFS git repo
  git:
    repo: "{{ afs_client_build_repo }}"
    dest: "{{ afs_client_build_path }}"
    version: "{{ afs_client_build_version }}"

- name: Generate autoconf scripts
  command: ./regen.sh
  args:
    chdir: "{{ afs_client_build_path }}"
  changed_when: false

- name: Configure
  command: >
    ./configure
    --with-afs-sysname={{ afs_client_sysname | default('amd64_linux26') }}
    {{ afs_client_configure_opts | default(_afs_client_configure_opts) }}
  args:
    chdir: "{{ afs_client_build_path }}"
  changed_when: false
  environment: "{{ afs_client_configure_env | default(_afs_client_configure_env) }}"

- name: Make build directory
  file:
    path: /tmp/openafs-client-build
    state: directory

- name: Make install
  make:
    chdir: "{{ afs_client_build_path }}"
    target: install
    params:
      DESTDIR: /tmp/openafs-client-build

- include_tasks: "{{ ansible_os_family|lower }}/install-files.yaml"
