---
- name: Add OpenAFS yum repo
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_openafs_client_repourl }}"
    gpgcheck: no

- name: Install OpenAFS base packages
  yum:
    state: present
    name:
      - openafs
      - openafs-krb5

- name: Query installed OpenAFS version
  shell: rpm -q --queryformat "%{VERSION}" openafs
  args:
    warn: False
  register: rpm_query
  changed_when: False

- name: Set kernel module package version
  set_fact:
    afs_openafs_kmod_version: "{{ rpm_query.stdout }}"
    afs_openafs_kmod_release: "{{ afs_openafs_kmod_prefix }}.{{ ansible_kernel | regex_replace('-','_') }}"

- name: Install OpenAFS kernel module
  yum:
    state: present
    name:
      - openafs-client
      - kmod-openafs-{{ afs_openafs_kmod_version }}-{{ afs_openafs_kmod_release }}
