---
- name: Add OpenAFS yum repo
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_openafs_client_repourl }}"
    gpgcheck: no

- name: Install OpenAFS client packages with DKMS
  yum:
    state: present
    name:
      - openafs
      - openafs-krb5
      - openafs-client
      - dkms
      - kernel-devel
      - dkms-openafs
