---
- name: Trace repo url
  debug:
    var: afs_server_repo_url

- name: Add OpenAFS yum repo
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_server_repo_url }}"
    gpgcheck: no

- name: Install OpenAFS server packages
  yum:
    state: present
    name:
      - openafs-server
      - openafs-krb5

- name: Set bosserver startup options
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ afs_bosserver_opts }}"'
    state: present
  notify:
    - Restart OpenAFS servers
