---
- name: restart kdc
  service:
    name: "{{ afs_krbserver_kdc_service }}"
    state: restarted

- name: restart kadmin
  service:
    name: "{{ afs_krbserver_admin_service }}"
    state: restarted
