---
## Patch up the contexts for the directories and files
## that were created while in unconfined_t
- name: "Restore directory contexts for selinux"
  command: restorecon -ir {{ item }}
  with_items:
    -  /usr/afs
    -  /usr/vice
  when: afs_selinux_mode == 'enforcing'

## Same -- for the partitions
- name: "Restore partition contexts for selinux"
  command: restorecon /vicep{{ item }}
  with_items: "{{ afs_partitions }}"
  when: afs_partitions is defined and afs_selinux_mode == 'enforcing'

- name: Start the OpenAFS servers
  service:
    name: openafs-server
    state: started
    enabled: yes
