---
- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit afs3 traffic
  firewalld:
    port: 7000-7009/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: Setup SELinux mode
  selinux:
    state: "{{ afs_selinux_mode }}"
    policy: targeted

- name: Setup SELinux policies
  include_tasks: "{{ ansible_os_family|lower }}/selinux.yaml"
  when: afs_selinux_mode == 'enforcing' or afs_selinux_mode == 'permissive'
