---
- name: Verify the admin password is defined
  fail:
    msg: |
      Please define afs_admin_password before running this role.
      It may be defined as a group variable (preferably encrypted
      with ansible-vault) or provided on the command line with
      the --extra-vars (-e) option.
  when: afs_admin_password is not defined

- name: Load OS specific variables
  include_vars: "{{ ansible_os_family|lower }}.yaml"

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family|lower }}.yaml"

- name: Configure kerberos kdc
  template:
    src: "{{ item }}.j2"
    dest: "{{ afs_kerberos_localstatedir }}/krb5kdc/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
  - kdc.conf
  - kadm5.acl
  notify:
    - restart kdc
    - restart kadmin

- name: Create kerberos kdc database
  command: >
    {{ afs_kdb5_util }}
    -P {{ afs_kerberos_master_password }}
    -r {{ afs_realm }}
    create -s
  args:
    creates: "{{ afs_kerberos_localstatedir }}/krb5kdc/principal"
  register: krb5_util_results

- name: Start kerberos kdc
  service:
    name: krb5kdc
    enabled: yes
    state: started

- name: Start kadmin
  service:
    name: kadmin
    enabled: yes
    state: started

- name: Create admin principal
  command: >
    {{ afs_kadmin_local }}
    -r {{ afs_realm }}
    -q "add_principal -pw {{ afs_admin_password }} {{ afs_admin_principal }}@{{ afs_realm }}"
  register: kadmin_results
  changed_when: >
    kadmin_results.rc == 0
    and not "already exists while creating" in kadmin_results.stderr
