---

- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit afs3 traffic
  firewalld:
    port: 7000-7009/udp
    immediate: yes
    permanent: yes
    state: enabled

- name: Setup SELinux mode
  selinux:
    state: "{{ selinux_mode }}"
    policy: targeted

- name: Setup SELinux policies
  include_tasks: selinux.yaml
  when: selinux_mode == 'enforcing'

- name: Add epel yum repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Add OpenAFS yum repo
  yum:
    name: "{{ openafs_yum_repo }}"
    state: present
    update_cache: yes

- name: Install OpenAFS server packages
  yum:
    state: present
    name:
      - openafs-server

- name: Set bosserver options
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: '^BOSSERVER_ARGS='
    line: 'BOSSERVER_ARGS="{{ opt_bosserver }}"'
    state: present
