---
- name: Start firewall
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit afs3 traffic
  firewalld:
    port: 7000-7009/udp
    immediate: yes
    permanent: yes
    state: enabled
