---
- name: Verify the admin password is defined
  fail:
    msg: |
      Please define afs_admin_password before running this role.
      It may be defined as a group variable (preferably encrypted
      with ansible-vault) or provided on the command line with
      the --extra-vars (-e) option.
  when: afs_admin_password is not defined

- include_vars: "{{ ansible_os_family|lower }}.yaml"

- name: Create cell-wide configuration files
  run_once: true
  local_action:
    module: template
    src: "{{ item }}.j2"
    dest: "{{ inventory_dir }}/files/{{ item }}"
  with_items:
    - CellServDB
    - ThisCell
    - UserList

- name: Create the Kerberos service key
  command: >
    {{ afs_kadmin }}
    -w {{ afs_admin_password }}
    -p {{ afs_admin_principal }}@{{ afs_realm }}
    -r "{{ afs_realm }}"
    -q "add_principal -randkey afs/{{ afs_cell }}@{{ afs_realm }}"
  register: kadmin_results
  changed_when: >
    kadmin_results.rc == 0
    and not "already exists while creating" in kadmin_results.stderr
  when: inventory_hostname == ansible_play_hosts[0]

- include_tasks: "{{ ansible_os_family|lower }}/pre-install.yaml"
- include_tasks: "{{ ansible_os_family|lower }}/install-{{ afs_server_install_method }}.yaml"
- include_tasks: "{{ ansible_os_family|lower }}/post-install.yaml"
- include_tasks: common/partitions.yaml
- include_tasks: common/config.yaml
- include_tasks: common/setkey-rxkad-krb5.yaml
- include_tasks: "{{ ansible_os_family|lower }}/post-config.yaml"

# The first admin user must be created with -localauth.
- include_tasks: common/admin-user.yaml
  when: inventory_hostname == ansible_play_hosts[0]

# The root.afs volume must exist before non-dynroot clients can mount /afs.
- include_tasks: common/root-afs-volume.yaml
  when: inventory_hostname == ansible_play_hosts[0]
