---
- include_tasks: "{{ ansible_os_family|lower }}/install-build-tools.yaml"

- name: Create build directory
  file:
    state: directory
    path: "{{ afs_server_build_path }}"

- name: Clone OpenAFS git repo
  git:
    repo: "{{ afs_server_build_repo }}"
    dest: "{{ afs_server_build_path }}"
    version: "{{ afs_server_build_version }}"

- name: Generate autoconf scripts
  command: ./regen.sh
  args:
    chdir: "{{ afs_server_build_path }}"
  changed_when: false

- name: Configure
  command: >
    ./configure
    --with-afs-sysname={{ afs_server_sysname | default('amd64_linux26') }}
    {{ afs_server_configure_opts | default(_afs_server_configure_opts) }}
  args:
    chdir: "{{ afs_server_build_path }}"
  changed_when: false
  environment: "{{ afs_server_configure_env | default(_afs_server_configure_env) }}"

- name: Build and install
  make:
    chdir: "{{ afs_server_build_path }}"
    target: install_nolibafs

- include_tasks: "{{ ansible_os_family|lower }}/install-files.yaml"
