---
- name: Create cell configuation directory
  file:
    state: directory
    path: "{{ afs_afsconfdir }}"
    mode: 0755
    owner: root
    group: root

- name: Update cell configuration
  copy:
    src: "{{ afs_openafs_server_tmpdir }}/{{ afs_cell }}/{{ item }}"
    dest: "{{ afs_afsconfdir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - CellServDB
    - ThisCell
    - UserList

- name: Set authentication realm
  copy:
    content: "{{ afs_realm }}"
    dest: "{{ afs_afsconfdir }}/krb.conf"
    mode: 0644
    owner: root
    group: root
  when: afs_realm is defined and afs_realm.lower() != afs_cell

- name: Create local server directory
  file:
    state: directory
    path: "{{ afs_afslocaldir }}"
    mode: 0700
    owner: root
    group: root

- name: Update local server configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ afs_afslocaldir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - NetInfo
  notify:
    - Restart OpenAFS servers

- name: Create BosServer configuration directory
  file:
    state: directory
    path: "{{ afs_bosconfdir }}"
    owner: root
    group: root

- name: Update BosServer server configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ afs_bosconfdir }}/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - BosConfig.new
  notify:
    - Restart OpenAFS servers
