---
- name: Setup the Kerberos realm kdc
  hosts: afs_kdcs[0]
  pre_tasks:
    - name: Connecting
      wait_for_connection:
  roles:
    - openafs_krbserver
  tasks:
    - include_tasks: snapshot.yaml
      vars:
        libvirt_snapshot: 01-realm
