- name: Create snapshots
  when:
    - libvirt_domain is defined
    - libvirt_snapshot is defined
  block:
    - name: List snapshots
      delegate_to: localhost
      changed_when: false
      check_mode: false
      command: virsh snapshot-list "{{ libvirt_domain }}" --name
      register: libvirt_snapshots

    - name: Trace snapshots
      debug:
        var: libvirt_snapshots
        verbosity: 1

    - name: Create snapshot
      delegate_to: localhost
      changed_when: false
      check_mode: false
      command: virsh snapshot-create-as "{{ libvirt_domain }}" --name "{{ libvirt_snapshot }}"
      when: libvirt_snapshot not in libvirt_snapshots.get('stdout_lines', [])
