---
- name: Load OS specific variables
  include_vars: "{{ ansible_distribution }}.yaml"

- name: Admin login
  command: >
    klog.krb5
    -principal {{ admin_principal }}
    -password {{ admin_password }}
    -cell {{ cell }}
    -k {{ realm }}

- include: volumes-{{ ('-dynroot' in opt_afsd) | ternary('dynroot','nodynroot') }}.yaml
