---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution|lower }}{{ ansible_distribution_version }}.yaml"
    - "../vars/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yaml"
    - "../vars/{{ ansible_distribution|lower }}.yaml"
    - "../vars/{{ ansible_os_family|lower }}.yaml"
    - "../vars/defaults.yaml"

- include_tasks: "system-{{ afs_firewall }}.yaml"
  when: afs_firewall is defined

- include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"

- name: Configure kerberos
  template:
    src: krb5.conf.j2
    dest: "{{ afs_krbclient_krb5_conf }}"
    owner: root
    group: root
    mode: 0644
