---
- name: Gather variables for each operating system
  include_vars: "{{ ansible_os_family|lower }}.yaml"

- include_tasks: "fw-{{ afs_firewall }}.yaml"
  when: afs_firewall is defined

- include_tasks: "install-{{ ansible_pkg_mgr }}.yaml"

- name: Configure kerberos
  template:
    src: krb5.conf.j2
    dest: "{{ afs_krbclient_krb5_conf }}"
    owner: root
    group: root
    mode: 0644
